# Operaciones con matrices

In [4]:
A = [1 2;3 4]

2×2 Array{Int32,2}:
 1  2
 3  4

In [7]:
# Matriz por bloques
C = [A A; A A]

4×4 Array{Int32,2}:
 1  2  1  2
 3  4  3  4
 1  2  1  2
 3  4  3  4

In [8]:
C = [[A] ; [A]]

2-element Array{Array{Int32,2},1}:
 [1 2; 3 4]
 [1 2; 3 4]

In [10]:
# Suma de matrices
C = 2*A+ 3*A

2×2 Array{Int32,2}:
  5  10
 15  20

In [11]:
# Matriz de 3 por 3 de puros unos
A = ones(3,3)

3×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [84]:
matriz = zeros(5,5)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [85]:
vector = zeros(2)

2-element Array{Float64,1}:
 0.0
 0.0

In [12]:
B = [1 2; 3 4]

2×2 Array{Int32,2}:
 1  2
 3  4

In [13]:
 C = B*B

2×2 Array{Int32,2}:
  7  10
 15  22

In [15]:
C^3

2×2 Array{Int32,2}:
  4625   6750
 10125  14750

In [16]:
# Desarrollo en serie de Taylor
sin(A)

3×3 Array{Float64,2}:
 0.04704  0.04704  0.04704
 0.04704  0.04704  0.04704
 0.04704  0.04704  0.04704

In [17]:
# El seno entrada a entrada
sin.(B)

2×2 Array{Float64,2}:
 0.841471   0.909297
 0.14112   -0.756802

In [18]:
# Elemento por lemento
B .^3

2×2 Array{Int32,2}:
  1   8
 27  64

In [19]:
# Dimensiones de una matriz
size(B)

(2, 2)

In [20]:
# El tamaño de una matriz.
length(B)

4

In [ ]:
# Inversa de una matriz.
inv(B)

In [21]:
transpose(B)

2×2 LinearAlgebra.Transpose{Int32,Array{Int32,2}}:
 1  3
 2  4

In [22]:
# Agreagar la biblioteca linear algebra.
# indicar el contenido de un paquete.

using LinearAlgebra

In [25]:
tr(B)

5

In [27]:
det(B)

-2.0

In [28]:
eigvals(B)

2-element Array{Float64,1}:
 -0.3722813232690143
  5.372281323269014 

In [30]:
eigvecs(B)

2×2 Array{Float64,2}:
 -0.824565  -0.415974
  0.565767  -0.909377

In [31]:
?diag

search: diag diagm diagind Diagonal isdiag Bidiagonal Tridiagonal SymTridiagonal



```
diag(M, k::Integer=0)
```

The `k`th diagonal of a matrix, as a vector.

See also: [`diagm`](@ref)

# Examples

```jldoctest
julia> A = [1 2 3; 4 5 6; 7 8 9]
3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

julia> diag(A,1)
2-element Array{Int64,1}:
 2
 6
```


In [34]:
# Una rango de numeros. EN general el uso de rangos está optimizado en Julia
rango = 1:10

1:10

In [33]:
typeof(rango)

UnitRange{Int32}

In [36]:
rango .^2

10-element Array{Int32,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [41]:
sin.(0:0.1:2pi )

63-element Array{Float64,1}:
  0.0                
  0.09983341664682815
  0.19866933079506122
  0.2955202066613396 
  0.3894183423086505 
  0.479425538604203  
  0.5646424733950355 
  0.6442176872376911 
  0.7173560908995228 
  0.7833269096274834 
  0.8414709848078965 
  0.8912073600614354 
  0.9320390859672264 
  ⋮                  
 -0.9258146823277321 
 -0.8834546557201531 
 -0.8322674422239008 
 -0.7727644875559871 
 -0.7055403255703919 
 -0.6312666378723208 
 -0.5506855425976376 
 -0.4646021794137566 
 -0.373876664830236  
 -0.27941549819892586
 -0.18216250427209502
 -0.0830894028174964 

In [40]:
# Arreglos con rangos. Los rangos se usan para generar arreglos. 
sqrt.((0:3:10).^2)

4-element Array{Float64,1}:
 0.0
 3.0
 6.0
 9.0

In [44]:
# Operaciones con rangos como conjunto de datos. \cap \cup con tabulador. 
(1:10) ∩ (0:2:10)


2:2:10

# Bloque de codigos
Secciones de bloques de codigos indicados por tabulador. Se usan para condicionales. Sirven para distinguir las acciones por ejemplo. 

In [52]:
if true
    print("Hola, Mundo!")
end

Hola, Mundo!

In [58]:
valor = 2
if valor !=0
    division = 1/valor
    print("$division")
end

0.5

In [59]:
valor = 0
if valor !=0
    division = 1/valor
    print("$division")
else
    print("error")
end

error

In [62]:
nombre = "Maria" 
if nombre == "pepe"
    print("Hola pepe")
elseif nombre == "Toño"
    nombre("Hola toño")
elseif nombre == "Maria"
    print("No te conozco")
end

No te conozco

# Ciclos y bucles 

In [63]:
arreglo = [6,7,8,4,5,6]
length(arreglo)

6-element Array{Int32,1}:
 6
 7
 8
 4
 5
 6

In [68]:
for elementos in arreglo
    println(elementos)
end   

6
7
8
4
5
6


In [71]:
for numero in  0:1
    for numero2 in 5:7
        if numero2 == 6
            continue
        end
        println(numero, numero2)
    end
end

05
07
15
17


In [72]:
for numero in  0:1
    for numero2 in 5:7
        if numero2 == 6
            break
        end
        println(numero, numero2)
    end
end

05
15


In [80]:
# Ciclo while
i = 0
while i<10
    i = i+1
    println("paso: ", i)
    end
end

paso: 1
paso: 2
paso: 3
paso: 4
paso: 5
paso: 6
paso: 7
paso: 8
paso: 9
paso: 10
paso: 11


In [81]:
# Ciclo while
i = 0
while true
    i = i+1
    println("paso: ", i)
    if i>9
        break
    end
end

paso: 1
paso: 2
paso: 3
paso: 4
paso: 5
paso: 6
paso: 7
paso: 8
paso: 9
paso: 10


# Funciones
- Las funciones tambien son un tipo de dato.

In [86]:
# Las fucniones sencillas. 
cuadrado(x) = x^2

cuadrado (generic function with 1 method)

In [87]:
cuadrado(3)

9

In [88]:
#Funcion que te saluda con tu nombre
saludo(nombre) = "Hola $nombre, ¿Como estas?"

saludo (generic function with 1 method)

In [91]:
saludo("Luis")

"Hola Luis, ¿Como estas?"

In [92]:
# Restringir el tipo de dato que la funcion puede o deba usar
saludo(nombre::String) = "Hola $nombre, ¿Como estas?"

saludo (generic function with 2 methods)

In [93]:
saludo.(["Luis", "Antonio", "Adolfo"])

3-element Array{String,1}:
 "Hola Luis, ¿Como estas?"   
 "Hola Antonio, ¿Como estas?"
 "Hola Adolfo, ¿Como estas?" 

In [94]:
saludo_2(nombre, apellido) = "Hola $nombre $apellido"

saludo_2 (generic function with 1 method)

In [95]:
saludo_2("Luis", "Diaz")

"Hola Luis Diaz"

In [104]:
function f(x=0)
    if x<=0
        return x^2
    else 
        return x
    end
end

f (generic function with 2 methods)

In [105]:
f()

0

In [103]:
arreglo = -10:10
f.(arreglo)

21-element Array{Int32,1}:
 100
  81
  64
  49
  36
  25
  16
   9
   4
   1
   0
   1
   2
   3
   4
   5
   6
   7
   8
   9
  10

In [107]:
function hello()
   return "Hola mundo"
end
    

hello (generic function with 1 method)

In [108]:
hello()

"Hola mundo"

In [122]:
function f(x,y;w =12)
    if x<=0
        return w^(xy)
    else
        return y*x*w
    end
end

f (generic function with 3 methods)

In [124]:
f(3,5,w=1)

15

In [ ]:
# Project euler codewars